### ISSUE TITLE
When a command with an alias is deleted, an error occurs in the setting panel

### ISSUE THREAD

**Issue by yajamon** [yajamon/obsidian-command-alias-plugin#35]
### Describe the bug

When a command with an alias is deleted, an error occurs in the setting panel.

### To Reproduce

1. Add a community plugin that adds commands to Obsidian
2. Add an alias to the command in that community plugin
3. Remove the community plugin
4. Open the CommandAlias configuration panel

### Expected behavior

A list of aliases is displayed.

### Screenshots

![image](https://github.com/yajamon/obsidian-command-alias-plugin/assets/6084855/4cfc78ee-5eed-49e1-82fa-a4dfc31f2175)

### Enviroment

- Plugin Version: 2.1.0
- Obsidian Version: 1.5.12
- Platform OS: Windows
- Platform OS Version: Windows 11

### Additional context

```txt
TypeError: Cannot read properties of undefined (reading 'name')
    at CommandAliasPluginSettingTab.display (plugin:obsidian-command-alias-plugin:77:35)
    at t.openTab (app.js:1:2960384)
    at t.openTabById (app.js:1:2960966)
    at t.onOpen (app.js:1:2961069)
    at e.open (app.js:1:1455869)
    at Object.callback (app.js:1:2980664)
    at oK (app.js:1:1987610)
    at e.executeCommand (app.js:1:1989143)
    at e.onTrigger (app.js:1:1164833)
    at e.handleKey (app.js:1:757237)
```

**Comment by yajamon** [comment]
https://github.com/yajamon/obsidian-command-alias-plugin/blob/698cb53a5dd32626c22f58722bf04e7168b84c4b/src/setting-tab.ts#L75
Check if it exists.
